name: Selenium Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  selenium-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Install ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        with:
          chrome-version: 'latest'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium
      - name: Start HTTP server
        run: |
          python3 -m http.server 8000 &
          sleep 3
      - name: Run Selenium test
        run: |
          python test_selenium.py
